version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/project

orbs:
  amark-tests1-orb: amark/amark-tests1-orb@volatile

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv

  test:
    executor: default
    steps:
      - checkout
      - amark-tests1-orb/fetch_rerun_vars:
          delete_env_var: true
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            echo "Bs Tests: $BS_ENV_VARS"
            source venv/bin/activate
            export PYTHONPATH=src

            if [[ -n "$BS_ENV_VARS" ]]; then
              echo "Running only rerun tests: $BS_ENV_VARS"
              pytest
            else
              echo "No rerun tests found, running full test suite."
              pytest
            fi

  deploy:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - amark-tests1-orb/fetch_rerun_vars
      - run:
          name: Deploy application
          command: |
            echo "Bs Tests: $BS_ENV_VARS"
            echo "Deploying Python application..."

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - amark-tests1-orb/cleanup_env:
          requires: [test , deploy]
