version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/project

orbs:
  amark-tests1-orb: amark/amark-tests1-orb@volatile

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv

  test:
    executor: default
    steps:
      - checkout
      - amark-tests1-orb/fetch_rerun_vars:
          delete_env_var: true
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            pip install pytest-html
            export PYTHONPATH=$PWD
            mkdir -p test-results artifacts
            pytest \
              --junitxml=test-results/junit.xml \
              --html=artifacts/report.html \
              --self-contained-html
      - run:                                              
          name: Generate large artifacts for memory test
          command: |
            yes "memtest-line-for-intg-2823" | head -c 5242 > artifacts/big.log
            ls -lh artifacts/
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: artifacts
          destination: test-artifacts
      - store_artifacts:
          path: test-results
          destination: junit


  deploy:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - amark-tests1-orb/fetch_rerun_vars
      - run:
          name: Deploy application
          command: |
            echo "Bs Tests: $BS_ENV_VARS"
            echo "Deploying Python application..."

workflows:
  version: 2
  ci_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
      - amark-tests1-orb/cleanup_env:
          requires: [test , deploy]
